### ISSUE TITLE
deleteLayer never returns

### ISSUE THREAD

**Issue by hbredin** [marc-j/camomile-server#1]
``` python
corpus = client.createCorpus(name='corpus', returns_id=True)
layer = client.createLayer(corpus, name='layer', returns_id=True)
client.deleteLayer(layer)  
```

This last line never returns.

**Comment by marc-j** [comment]
The Layer.removeWithEvent doesn't execute callback  [https://github.com/marc-j/camomile-server/blob/develop/models/Layer.js#L129](https://github.com/marc-j/camomile-server/blob/develop/models/Layer.js#L129).
It's same in all models using removeWithEvent function.
 I'll fix it
