### ISSUE TITLE
Uploaded metadata files are not deleted when replaced by metadata value

### ISSUE THREAD

**Issue by hbredin** [marc-j/camomile-server#5]
This works fine (it creates a file somewhere in the `upload` directory)

```
import tempfile
_, localPathToFile = tempfile.mkstemp()
with open(localPathToFile, 'w') as fp:
     fp.write('blah blah blah')
client.sendCorpusMetadataFile(corpus, 'key.subkey', localPathToFile)
```

However, if this metadata is replaced, the file in the `upload` directory is not deleted.

```
client.setCorpusMetadata(corpus, 'value', path='key.subkey')
```

This is an issue because the `upload` directory will eventually contain a lot of orphan files.
I guess (but I did not check) the same behavior happens when
- a whole metadata subtree is replaced by another one
- a whole metadata subtree is deleted
- a metadata of type "file" is deleted

**Comment by marc-j** [comment]
The file is not deleted because it should create a loop on the entire tree for delete all files in subtree.
If metadata subtree is replaced, it should request the last entry for check if type is file or not. 

In metadata structure this would require for all subtree on create/update, read current data in mongo and it's very heavy

**Comment by hbredin** [comment]
It would indeed be very heavy but it might end up in very large `upload` directory full of orphan files -- which is not a good thing...

Maybe we could implement some kind of garbage collector to clean the `upload` directory on a periodic basis? I am not sure how this can be done efficiently, though...

**Comment by hbredin** [comment]
Looks like there are still some files not being deleted when the method is **overwriten**.

For instance, the second line below should delete the copy of `file1`, shouldn't it?

``` python
client.sendCorpusMetadataFile(corpus, 'key', '/path/to/file1') 
client.sendCorpusMetadataFile(corpus, 'key', '/path/to/file2')   
```

Similarly, this should also delete the copy of `file1`, but it doesn't seem to...

``` python
client.sendCorpusMetadataFile(corpus, 'key', '/path/to/file1') 
client.deleteCorpusMetadata(corpus, 'key')
```

**Comment by marc-j** [comment]
File delete is call before, file creating (async).

try :

``` python
client.sendCorpusMetadataFile(corpus, 'key', '/path/to/file1') 
sleep(1)
client.sendCorpusMetadataFile(corpus, 'key', '/path/to/file2')  
```

``` python
client.sendCorpusMetadataFile(corpus, 'key', '/path/to/file1') 
sleep(1)
client.deleteCorpusMetadata(corpus, 'key')
```

**Comment by hbredin** [comment]
Oooops, sorry. I was using an old "cached" docker container...
Deleting (or overwriting) actually works fine -- though the resulting empty directory structure remains.

There is still a corner case that does not work:

``` python
client.sendCorpusMetadataFile(corpus, 'key', '/path/to/file1')
sleep(1) 
client.sendCorpusMetadataFile(corpus, 'key.subkey', '/path/to/file2')   
```

After those two lines, the copy of `file1` is still there.

**Comment by marc-j** [comment]
Delete file check update on 'key'. 
'key.subkey' doesn't match 'key' and key.subkey is considered a child of 'key', thats wy's file is not deleted

**Comment by hbredin** [comment]
``` python
>>> client.sendCorpusMetadataFile(corpus, 'key', '/path/to/file1')
>>> sleep(1) 
>>> client.sendCorpusMetadataFile(corpus, 'key.subkey', '/path/to/file2')   
>>> sleep(1)
>>> client.getCorpusMetadata(corpus, 'key')
{u'subkey': {u'filename': u'file2',
  u'type': u'file',
  u'url': u'/corpus/573b18ff65cd28430195668b/metadata/key.subkey?file'}}
```

There are no longer any metadata at path `key` once `key.subkey` is set.
`file1` is gone: it should therefore be deleted as well, shouldn't it?

**Comment by marc-j** [comment]
This is a limitation of the structure
In mongo, key is always stored, because is not rewrited by key.subkey.

The tree constructor ignore 'key' because 'key.subkey' overwrite 'key' and it is not display in result.

**Comment by hbredin** [comment]
It makes sense that `key` is no longer a leaf of the tree and is lost once a `subkey` is set.
This behavior is perfectly fine:

``` python
>>> client.setCorpusMetadata(corpus, 'key', 'value')
>>> client.setCorpusMetadata(corpus, 'key.subkey', 'other_value')   
>>> client.getCorpusMetadata(corpus, 'key')
{u'subkey': u'other_value'}
```

`value` is lost and it is the expected behavior.

However, when `value` is in fact a file, it should be lost (i.e. deleted) as well.
Otherwise, the initial problem remains the same: we might end up with a lot of orphan files in the `upload` directory.

**Comment by marc-j** [comment]
Solution is use a task for check tree integrity which remove trees overwritten.

**Comment by marc-j** [comment]
I found solution, for not use a task
